fix composite action

diff --git a/.github/actions/tag-action/action.yaml b/.github/actions/tag-action/action.yaml
--- a/.github/actions/tag-action/action.yaml
+++ b/.github/actions/tag-action/action.yaml
@@ -17,14 +17,13 @@ runs:
   using: "composite"
   steps:
     - run: |
-        run: |
-          SUB='-rc'
-          if [[ "${{ inputs.ORIGINAL_TAG }}" == *"${{ inputs.SUB_STRING }}"* ]]; then
-              echo "Release candidate tag found."
-          else
-              echo "Release candidate tag not found."
-              exit 1
-          fi
+        SUB='-rc'
+        if [[ "${{ inputs.ORIGINAL_TAG }}" == *"${{ inputs.SUB_STRING }}"* ]]; then
+            echo "Release candidate tag found."
+        else
+            echo "Release candidate tag not found."
+            exit 1
+        fi
       shell: bash
 
 
@@ -36,38 +35,3 @@ runs:
           echo "New tag: $NEW_TAG"
           echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
       shell: bash
-      
-    #   echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
-
-    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
-    #   shell: bash
-    # - run: goodbye.sh
-    #   shell: bash
-
-
-
-
-
-
-      # - name: tag validator
-      #   run: |
-      #     SUB='-rc'
-      #     if [[ "${{ env.ORIGINAL_TAG }}" == *"$SUB"* ]]; then
-      #         echo "Release candidate tag found."
-      #     else
-      #         echo "Release candidate tag not found."
-      #         exit 1
-      #     fi
-
-      # - name: tag-calculator
-      #   id: tag-calculator     
-      #   run: | 
-      #     NEW_TAG=
-      #     echo "Original tag: ${{ env.ORIGINAL_TAG }}"
-      #     NEW_TAG=$(echo ${{ env.ORIGINAL_TAG }} | awk -F '-rc' '{print $1}')
-      #     echo "New tag: $NEW_TAG"
-      #     echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
-
-      # - name: echo new tag
-      #   run: echo ${{ steps.tag-calculator.outputs.NEW_TAG }}
-
