add composite action

diff --git a/.github/workflows/02-release.yaml b/.github/workflows/02-release.yaml
--- a/.github/workflows/02-release.yaml
+++ b/.github/workflows/02-release.yaml
@@ -18,27 +18,29 @@ jobs:
       ORIGINAL_TAG: ${{ github.ref_name }}
     runs-on: ubuntu-latest
     steps:
-      - name: tag validator
-        run: |
-          SUB='-rc'
-          if [[ "${{ env.ORIGINAL_TAG }}" == *"$SUB"* ]]; then
-              echo "Release candidate tag found."
-          else
-              echo "Release candidate tag not found."
-              exit 1
-          fi
+      - id: tag-calcilator
+        uses: actions/tag-action@v1
+      # - name: tag validator
+      #   run: |
+      #     SUB='-rc'
+      #     if [[ "${{ env.ORIGINAL_TAG }}" == *"$SUB"* ]]; then
+      #         echo "Release candidate tag found."
+      #     else
+      #         echo "Release candidate tag not found."
+      #         exit 1
+      #     fi
 
-      - name: tag-calculator
-        id: tag-calculator     
-        run: | 
-          NEW_TAG=
-          echo "Original tag: ${{ env.ORIGINAL_TAG }}"
-          NEW_TAG=$(echo ${{ env.ORIGINAL_TAG }} | awk -F '-rc' '{print $1}')
-          echo "New tag: $NEW_TAG"
-          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
+      # - name: tag-calculator
+      #   id: tag-calculator     
+      #   run: | 
+      #     NEW_TAG=
+      #     echo "Original tag: ${{ env.ORIGINAL_TAG }}"
+      #     NEW_TAG=$(echo ${{ env.ORIGINAL_TAG }} | awk -F '-rc' '{print $1}')
+      #     echo "New tag: $NEW_TAG"
+      #     echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
 
-      - name: echo new tag
-        run: echo ${{ steps.tag-calculator.outputs.NEW_TAG }}
+      # - name: echo new tag
+      #   run: echo ${{ steps.tag-calculator.outputs.NEW_TAG }}
 
 
   binary-build:
